### ISSUE TITLE
Text is brighter than the previous release

### ISSUE THREAD

**Issue by sclu1034** [wez/wezterm#1025]
## Describe the bug

After getting a "new release" notification today, I switched from a version from June (`wezterm-git (wezterm.ssh.0.1.1.120.g20c4dcdc-1)`) to a nightly build (`wezterm-nightly-bin (20210815.182117.ab21910d-1)`).
I immediately noticed multiple changes to how the content is rendered, compared to instances of the previous version I still have running.

- The cursor sometimes has "fuzzy" edges, compared to the previously sharp edges.
  - With my custom "Gruvbox Light Soft" colour scheme, this happens for active panels, while the inactive ones are fine
  - With the default colour scheme, it's the other way around
- Text is now bold(er) and colours have changed slightly
- Contrary to the text getting bolder, the character used to render the separator between panes is now thinner. It's also used in Kakoune, where the change is the same.
- Dimming for inactive panes doesn't affect the background colour any more. Only the text colour changes.
  - It does work again when the inactive pane is running Kakoune.

## Environment:

 - OS: Linux X11
 - Version: `wezterm 20210815-182117-ab21910d`

## Configuration

**Font settings:**
```lua
font = wezterm.font("Hack Nerd Font"),
font_size = 14,
```

**Colour Scheme:**
```toml
# Gruvbox Light Soft
[colors]
background = "#f2e5bc"
foreground = "#3c3836"
cursor_bg = "#3c3836"
cursor_border = "#f2e5bc"
cursor_fg = "#f2e5bc"

# black, red, green, yellow, blue, purple, teal, white
ansi = ["#282828","#cc241d","#98971a","#d79921","#458588","#b16286","#689d6a","#928374"]
brights = ["#7c6f64","#9d0006","#79740a","#b57614","#076678","#8f3f71","#427b58","#7c6f64"]
```

## Screenshots

**Fuzzy cursor:**
![image](https://user-images.githubusercontent.com/4508454/129547267-884dbfe8-16d0-481f-845c-a95b5f6b91f3.png)

**Bold text, different colours:**
Old version is top.
![image](https://user-images.githubusercontent.com/4508454/129547644-2fa963c0-be4d-4ca4-ae9b-5b47649dff12.png)

**Active vs Dimmed:**
Active is top.
![image](https://user-images.githubusercontent.com/4508454/129548096-5bef0712-7ba7-4cbd-a8e5-764a20fb603b.png)
