### ISSUE TITLE
Size at startup

### ISSUE THREAD

**Issue by erf** [wez/wezterm#142]
Could you add a config for setting size `cols` and `rows` at startup ?

**Comment by wez** [comment]
When the next nightly build is published (in ~1 hour from now), you'll be able to specify:

```toml
initial_rows = 40
initial_cols = 100
```
