### ISSUE TITLE
only renders in small part of window in i3

### ISSUE THREAD

**Issue by ExpandingMan** [wez/wezterm#1710]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220310-055045-d5391fa5

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm renders itself in a little corner of the actual window, as pictured (what you are seeing around it is the background).  It looks normal when I go into fullscreen, but if I get out of fullscreen it shows a full but blank window (only background color, nothing visible).
![2022-03-10-120651_1166x590_scrot](https://user-images.githubusercontent.com/11379353/157717447-e722ee94-fbf3-42c9-a0c7-439e13ddb198.png)

### To Reproduce

Run wezterm in my environment.

### Configuration

no config

(screenshot above is with a config, but same behavior as no config)

### Expected Behavior

Wezterm fills the window.

### Logs

2022-03-10T17:13:32.096Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-771615
 2022-03-10T17:13:32.205Z INFO  wezterm_gui::termwindow        > OpenGL initialized! NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 4.6.0 NVIDIA 510.54 is_context_loss_possible=false wezterm version: 20220310-055045-d5391fa5

**Comment by ExpandingMan** [comment]
Sorry for my glib way of putting that but obviously I'm not going to upload a disk image, so I didn't exactly know what was relevant.

I just ran `i3` with no config and get the same behavior.  Note that this is `i3-gaps` on Manjaro, specifically
```
i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
```
As you can see above, this is with proprietary nvidia drivers.
```
System:
  Host: asus-desk-1 Kernel: 5.15.25-1-MANJARO x86_64 bits: 64
    Desktop: i3 4.20.1 Distro: Manjaro Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: TUF GAMING X570-PLUS (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI-[Legacy]: American Megatrends v: 0807
    date: 07/08/2019
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080 SUPER] driver: nvidia v: 510.54
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1: 2560x1440~144Hz 2: 2560x1440~144Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.54
```
