### ISSUE TITLE
Save and load layouts

### ISSUE THREAD

**Issue by JakeHL** [wez/wezterm#1949]
**Is your feature request related to a problem? Please describe.**
I find it frustrating when I have to open up a terminal, configure my pane how I like them and run the relevant tools in each pane.

**Describe the solution you'd like**
This suggestion is heavily inspired by [layouts](https://zellij.dev/documentation/layouts.html) in [zellij](https://github.com/zellij-org/zellij)

I think it would be great to have some form of config file that can be loaded that will automatically configure pane/tabs and the commands that are run inside them. These could be saved inside of source control alongside projects.

For example if I'm frequently opening a text editor, file browser, and terminal in wezterm for editing code maybe it could be loaded by typing `wz text-editor.yml` or something.

configs could be made by hand or exported from an existing layout.

I would vote to use yaml for the config, however I'm aware toml is more idiomatic in rust applications. Maybe lua would be a good idea to be in keeping with the config file.

an example of what the config could look like if it were yaml. I'm absolutely positive this could be better thought out.
```yaml
split:
  direction: vertical
  sections: 
    - split:
        direction: horizontal
      sections:
      - pane:
          cmd: 'br .'
          cwd: '.'
          width: '20%'
      - pane:
          cmd: 'nvim .'
    - pane:
        cmd: 'zsh'
        height: '10%'
```

**Describe alternatives you've considered**
Remembering the last used layout by directory was an option I considered, but having editable configs would make it really nice to store specific layouts alongside projects.

**Additional context**
I currently use zellij for this functionality however I really like the multiplexing in wezterm. Thanks for the great work!
