### ISSUE TITLE
[Help] Env variables in Lua?

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#204]
I don't have a very complicated configuration file... at least until I get to the environmental variables. I have absolutely no idea how to set the 'prompt' variable. Here's my toml file, as you can see, not very complicated... except for that prompt variable:
```toml
font_dirs = ["fonts"]
font_size = 13
font_locator = "ConfigDirsOnly"

[[font.font]]
family = "Iosevka Term Light Nerd Font Complete"

[set_environment_variables]
prompt = "$E]7;file://localhost/$P$E\\$E[32m$T$E[0m $E[35m$P$E[36m$_$G$E[0m "
```
I know even after I figure out how to set the env variables in Lua, I'm probably going to have to escape different characters. I'd really appreciate your guidance.
