### ISSUE TITLE
indexed colors no longer work?

### ISSUE THREAD

**Issue by chtenb** [wez/wezterm#2197]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My color schemes fail to load with the log error

```
failed to load: parsing TOML: Error processing colors.indexed (types: ColorSchemeFile, Palette) Cannot convert `String` to `u8`
```

### To Reproduce

I use the following toml file for my theme

```toml
[colors]
foreground = "#005661"
background = "#fef8ec"
cursor_bg = "#005661"
cursor_border = "#005661"
cursor_fg = "#ffffff"
selection_bg = "#cfe7f0"
selection_fg = "#005661"

ansi = [ "#8ca6a6" ,"#e64100" ,"#00b368" ,"#fa8900" ,"#0095a8" ,"#ff5792" ,"#00bdd6" ,"#005661" ]
brights = [ "#8ca6a6" ,"#e5164a" ,"#00b368" ,"#b3694d" ,"#0094f0" ,"#ff5792" ,"#00bdd6" ,"#004d57" ]

[colors.indexed] 
52 = "#fbdada" # minus
88 = "#f6b6b6" # minus emph
22 = "#d6ffd6" # plus
28 = "#adffad" # plus emph
53 = "#feecf7" # purple
17 = "#e5dff6" # blue
23 = "#d8fdf6" # cyan
58 = "#f4ffe0" # yellow
```

### Configuration

I just set the color_scheme_dirs setting.

### Expected Behavior

This scheme used to just work in I think the previous version (or the one before).

### Logs

failed to load: parsing TOML: Error processing colors.indexed (types: ColorSchemeFile, Palette) Cannot convert `String` to `u8`
