### ISSUE TITLE
Random underline in new `clap` help

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#2489]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway version 1.7

### WezTerm version

wezterm 20220905-171004-86c9d781

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the master clap version, I noticed that there is a random underline, that is not visible in alacritty and kitty, not 100% sure this is a wezterm bug, but due to working in the other two feels like it:

1. wezterm
2. alacritty
3. kitty

![grafik](https://user-images.githubusercontent.com/11978847/188613971-dcc50f90-dd17-4ed3-aaf4-17080ebbd805.png)

### To Reproduce

```toml
[package]
name = "footstep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap", version = "4.0.0-alpha.0", rev = "7ed7f71a1f9e2cd32c9564b35cc27df3b489a050" }
```

```rs
use clap::Command;

fn main() {
    Command::new("test").print_help();
}
```

```console
cargo run
```

### Configuration

no config

### Expected Behavior

The behavior should be the same as the others.

### Logs

No additonal log output on executing
