### ISSUE TITLE
Colors settings about `tab_bar` have no effect while `use_fancy_tab_bar` is `true`

### ISSUE THREAD

**Issue by expnn** [wez/wezterm#2615]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20221009-202607-cb31c35b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When `use_fancy_tab_bar` is set to true, the colors about `tab_bar` specified in the color_scheme file take no effect. 
However, we can define the 'format-tab-title' event to assign colors to tab_bar, so it is not a restriction of the fancy tab. 

Tried on both the latest release version and the nightly version:
- release: 20220905-102802-7d4b8249
- nightly: 20221009-202607-cb31c35b

### To Reproduce

Nothing special, just set the `color_scheme` and toggle the value of `use_fancy_tab_bar` to see the difference. 
The color scheme should have `tab_bar` section settings that are different from the default. I attached a custom color scheme in the configuration section, to reproduce.

### Configuration

- wezterm.lua

```lua

local wezterm = require("wezterm")

local config = {
    -- set use_fancy_tab_bar=true, wezterm does not respect the tab_bar settings 
    -- in the color_scheme file, while if it is turned off, the color specified is effective. 
    -- Note that we can define the 'format-tab-title' event to draw colors 
    -- irrelevent of `use_fancy_tab_bar`'s value. 
    use_fancy_tab_bar = true,

   -- a `custom.toml` file is placed in the `color` subdirectory relative to this configuration file, 
   -- the content of which is pasted below. 
    color_scheme = 'custom', 
}

-- We can define the 'format-tab-title' event to assign colors to tab_bar,
-- no matter what the `use_fancy_tab_bar` value is. 
-- uncomment it out to see the effect. 
-- wezterm.on('format-tab-title', function(tab, tabs, panes, config, hover, max_width)
--     local pane = tab.active_pane
--     local title_prefix = tostring(tab.tab_index + 1) .. ": "

--     if pane.domain_name then
--         title_prefix = title_prefix .. '[' .. pane.domain_name .. '] '
--     end
--     local title = title_prefix .. pane.title

--     if tab.is_active then
--         return {
--             { Background = { Color = '#bd93f9' } },
--             { Foreground = { Color = '#282a36' } },
--             { Text = ' ' .. title .. ' ' }
--         }
--     end
--     local has_unseen_output = false
--     for _, pane in ipairs(tab.panes) do
--         if pane.has_unseen_output then
--             has_unseen_output = true
--             break
--         end
--     end
--     if has_unseen_output then
--         return {
--             { Background = { Color = 'Orange' } }, 
--             { Text = ' ' .. title .. ' ' }
--         }
--     end
--     return title
-- end)

return config

```

- colors/custom.toml

```toml
[colors]
ansi = [
    '#282c34',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#abb2bf',
]
background = '#282c34'
brights = [
    '#545862',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#c8ccd4',
]

compose_cursor = '#ffb86c'
cursor_bg = '#98c379'
cursor_border = '#98c379'
cursor_fg = '#abb2bf'
foreground = '#abb2bf'
selection_bg = '#abb2bf'
selection_fg = '#282c34'
# selection_bg = 'rgba(26.666668% 27.843138% 35.294117% 50%)'
# selection_fg = 'rgba(0% 0% 0% 0%)'
scrollbar_thumb = '#44475a'
split = '#6272a4'

[colors.indexed]

[colors.tab_bar]
background = '#282a36'

[colors.tab_bar.active_tab]
bg_color = '#bd93f9'
fg_color = '#282a36'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#282a36'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#6272a4'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#282a36'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ff79c6'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'expnn <chenych11@gmail.com>'
name = 'custom'
```

### Expected Behavior

The `tab_bar` settings in the color scheme file should be respected. 

### Logs

nothing
