### ISSUE TITLE
[question] How to enable <C-CR> and <S-CR>?

### ISSUE THREAD

**Issue by Freed-Wu** [wez/wezterm#2692]
For alacritty

```yaml
key_bindings:
  - key: Return
    mods: Shift
    chars: "\x1b[13;2u"
  - key: Return
    mods: Control
    chars: "\x1b[13;5u"
```

And kitty

```ini
map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u
```

How about wezterm?
