### ISSUE TITLE
right arrow glyph is 1 pixel off point

### ISSUE THREAD

**Issue by thatboyjake** [wez/wezterm#3144]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230219-070657-23211fc8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With my starship config the glyph height is wrong
![image](https://user-images.githubusercontent.com/45983348/220701918-0ee643bc-a54b-4ecd-9702-1f75efd4edc2.png)
here in alacritty
![image](https://user-images.githubusercontent.com/45983348/220702199-66f7aa83-9e6b-4f3a-a7ba-9b0c3f3498a2.png)

### To Reproduce

This is my starship config
```toml
# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

[battery]
disabled = true
# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[docker_context]
format = "via [ $context](bold blue) "

[helm]
format = "via [ $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "

[kubernetes]
disabled = true
format = 'on [ $context\($namespace\)](bold purple) '
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"
```

### Configuration

No config

### Expected Behavior

for the glyph to line up like in alacritty

### Logs

Debug Overlay
wezterm version: 20230219-070657-23211fc8 x86_64-pc-windows-msvc
Window Environment: Windows
OpenGL version: Intel(R) UHD Graphics 620 4.5.0 - Build 30.0.101.3111
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

### Anything else?

from what I understand this is just a issue with custom_block_glyphs not catching the glyph
