### ISSUE TITLE
Define specific fonts for different variants

### ISSUE THREAD

**Issue by happenslol** [wez/wezterm#3457]
**Is your feature request related to a problem? Please describe.**
When configuring fonts to use in the terminal, wezterm allows defining multiple fonts in a sort of "priority list". When calling `wezterm ls-fonts`, the font that will be used in each situation (intensity, italic, etc.) is shown.

I generally use the medium variants of the terminal fonts I use, and substitute the regular font for places in which the light/extra light variant would normally be used (and likewise extrabold instead of bold). Currently, it's not possible for me to manually define the font variant I want to use in each situation,

**Describe the solution you'd like**
Other terminals I've used such as alacritty or kitty allow defining the font for regular, bold, italic and italic/bold separately.

For reference, the kitty config allows this:
```
font_family      Iosevka Term Nerd Font Complete Medium
bold_font        Iosevka Term Nerd Font Complete Extrabold
italic_font      Iosevka Term Nerd Font Complete Medium Italic
bold_italic_font Iosevka Term Nerd Font Complete Extrabold Italic
```

while the alacritty config provides this option:
```yaml
font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic
```

**Describe alternatives you've considered**
It seems like it's possible to define at least the default regular font like this:

```lua
config.font = w.font_with_fallback({
  { family = "IosevkaTerm Nerd Font Medium", weight = "Regular" },
})
```

However, the light and extralight variants still show up in my terminal.

**Additional context**
I'd be interested in implementing this myself, but I'd first like to know if this is something you've considered, or is hard to do due to the way fonts are resolved right now.

Thank you!
