### ISSUE TITLE
format-tab-title with string return value yields incorrect tab widths for hover

### ISSUE THREAD

**Issue by serhez** [wez/wezterm#3481]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-200110-397593be

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Tab hover on the tab bar highlights all tabs up until the actual tab being hovered, instead of just that one.

### Configuration

Snippet from `wezterm.lua`:

``` lua
return {
    enable_wayland = false,
    pane_focus_follows_mouse = false,
    front_end = "WebGpu",
    
    window_decorations = "RESIZE"
    
    inactive_pane_hsb = {
    saturation = 1.0,
    brightness = 0.85,
    },
    tab_bar_at_bottom = true,
    use_fancy_tab_bar = false,
    show_new_tab_button_in_tab_bar = false,
    show_tab_index_in_tab_bar = false,
    window_background_opacity = 1.0,
    tab_max_width = 50,
    hide_tab_bar_if_only_one_tab = false,
    switch_to_last_active_tab_when_closing_tab = true,
    
    color_scheme = "tokyonight-dark",
}
```

Snippet from `colors/tokyonight-dark.toml`:

```toml
[colors.tab_bar]
background = "#15161e"

[colors.tab_bar.active_tab]
bg_color = "#7aa2f7"
fg_color = "#15161e"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#33467c"
fg_color = "#c0caf5"
```

### Expected Behavior

Only the tab being hovered would be highlighted.

### Anything else?

A video of the bug:

https://user-images.githubusercontent.com/18057093/230769622-ccbf02e9-daf6-4f69-ac09-ea0d93064452.mov
