### ISSUE TITLE
SendString does not support byte sequences (and literals)

### ISSUE THREAD

**Issue by fanzeyi** [wez/wezterm#43]
With the following config:

```toml
[[keys]]
key = "m"
mods = "CMD"
action = "SendString"
args = "\x01\x02"
```

WezTerm fails with the following error message:

```
Error parsing TOML from /Users/fanzeyi/.wezterm.toml: invalid escape character in string: `x` at line 21
```

If I directly put the byte sequence in the configuration file like this (in Vim, `^V^B`):

```toml
[[keys]]
key = "m"
mods = "CMD"
action = "SendString"
args = ""
```

It fails with the following error message:

```
 ERROR wezterm > Error parsing TOML from /Users/fanzeyi/.wezterm.toml: invalid character in string: `\u{2}` at line 21
145:146: syntax error: Expected “"” but found unknown token. (-2741)
Error: ErrorMessage { msg: "Error parsing TOML from /Users/fanzeyi/.wezterm.toml: invalid character in string: `\\u{2}` at line 21" }
```

Byte escaping support is intentionally removed from TOML standard (toml-lang/toml#173).

----

**Proposal:** Adding another action `SendByte`. Since TOML standard does not support byte sequence escaping, `"\x01\x02"` is an invalid TOML string. Instead, we could be using TOML array to specify bytes in the form of `[0x1, 0x2]`. The configuration would look like:

```toml
[[keys]]
key = "m"
mods = "CMD"
action = "SendByte"
args = [0x02, 0x3b]
```
