### ISSUE TITLE
Alternative actions for hyperlinks (e.g., copy hyperlink on ctrl+mouse left)

### ISSUE THREAD

**Issue by fabian-thomas** [wez/wezterm#4371]
**Is your feature request related to a problem? Please describe.**
I'm currently using alacritty and would like to switch to wezterm for the multiplexing functionality. In alacritty one has the option to specify alernative actions for clicking on hyperlinks or links defined by regex and I would love to have that in wezterm as well. It's easiest to explain that with my current alacritty config (yaml):
```yaml
  # NOTE: this is just below but the following removed:
  # - ipv6
  # - ipv4
  # - hashs
  # - versions
  # - all words
  define: &link_regex "((ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|vnc:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+)\
            |[a-zA-Z0-9-_~./!?&@+]+/[a-zA-Z0-9-_~./!?&@]+(:[0-9]+)?(:[0-9]+)?\
            |[a-zA-Z0-9-_~./!?&@+]+(:[0-9]+)?:[0-9]+"

  define: &copy_regex "((ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|vnc:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+)\
            |([0-9a-fA-F]{1,4}:){1,7}([0-9a-fA-F]{1,4}){0,1}(:[0-9a-fA-F]{1,4}){1,7}\
            |[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\
            |[0-9a-f]{32,64}\
            |([0-9]+\\.)+[0-9]+(-[0-9]+)?\
            |[a-zA-Z0-9-_~./!?&@+]+/[a-zA-Z0-9-_~./!?&@]+(:[0-9]+)?(:[0-9]+)?\
            |[a-zA-Z0-9-_~./!?&@+]+(:[0-9]+)?:[0-9]+\
            |[a-zA-Z0-9-_~./!?&@+:]+"
            # description:
            # protocol links
            # ipv6/mac
            # ipv4
            # hashes/git commits (git log)
            # versions
            # files with colon + line
            # files with colon + line
            # all words without space or paren (check the set of characters)

  enabled:
    # these patterns both copy
    # we have two since only like that we can copy both text and hyperlink
    # hyperlink is Alt additionally
    # this is still not perfect since we need a regex for everything we want to copy with the
    # first mode. We could add a mode where we have hyperlinks true but use the underlying text
    # nevertheless.
  - regex: None
    hyperlinks: true
    action: Copy
    post_processing: true
    mouse:
      enabled: true
      mods: Control|Alt
  - regex: *copy_regex
    hyperlinks: false
    action: Copy
    post_processing: true
    mouse:
      enabled: true
      mods: Control

  - regex: *link_regex
    hyperlinks: true
    command:
      program: "open"
      args: ["--prompt"]
    post_processing: true
    mouse:
      enabled: true
      mods: Alt
  - regex: *link_regex
    hyperlinks: true
    command: open
    post_processing: true
    mouse:
      enabled: true
      mods: None
```
This config provides  me with the following functionality:
1. When I click any matched link (both by regex and native hyperlink) while holding CTRL, the **visible** text is copied to clipboard.
2. When I hold CTLR+ALT and click on a native (non-regex) hyperlink, the hyperlink is copied to clipboard.
3. When I click on a hyperlink or a regex hyperlink (note that I have two regex patterns, one for copy-only text and one for real links) the link is opened.
4. When I hold Alt and click on a link (as in 3.), I open the link while prompting for a program that should be used (note that this prompting is something I built myself and is not available in xdg-open).

**Describe the solution you'd like**
I'm not entirely sure how this could be integrated into the current configuration logic. I feel like hyperlinks and hyperlink_rules should be unified so that one can define keybindings for both together. At least we should consider adding the following:
- Custom actions for both hyperlinks and hyperlink rules based on mouse modifier or keyboard binding.
- Adding actions for copying the clicked text and the resulting hyperlink to clipboard (e.g., `ClipLinkAtCursor` and `ClipLinkTextAtCursor`).
- The clicked hyperlink could be exposed via lua. (e.g., `pane:get_cursor_hyperlink()`). Then one could script their own copy hyperlink.

Related: Wez did already think about unifying hyperlink configs in 2021 (https://github.com/wez/wezterm/issues/1362#issuecomment-1000457693).
