### ISSUE TITLE
`Enter` key binding does not work on macOS

### ISSUE THREAD

**Issue by fanzeyi** [wez/wezterm#53]
Version: WezTerm-macos-azure-20190626-162911-cc019ce-265-g30c6ac7
OS Version: macOS Mojave 10.14.6 (18G103)

The following key binding does not work:

```toml
[[keys]]
key = "Enter"
mods = "ALT"
action = "SendString"
arg = "hello"
```

I also tried other modifiers (`CTRL`, `CMD` and `SHIFT`). None of these works :(
