### ISSUE TITLE
just tell me how to disable links, please, please

### ISSUE THREAD

**Issue by colemickens** [wez/wezterm#5303]
**What page or section of the docs have an issue?**
I have been staring at the docs for 15 minutes. I have tried 5 different things. I have read three different issues, all with different answers that supposedly worked over the last 3+ years.

I just get error after error. Please, there **must** be a _simple_ way to make it so that mis-clicking in Alacritty doesn't just start spawning krita.

**Describe the issue**
A clear and concise description of what you were looking for, couldn't find, or
the where things were misleading etc.

**Comment by colemickens** [comment]
this is how things are going. As far as I can tell that regex line is copied straight from the documentation page.

![Screenshot_2024-04-15_20-14-04](https://github.com/wez/wezterm/assets/327028/732d50df-c2ec-42c8-88d0-bcc7fdcf5f69)

**Comment by colemickens** [comment]
woohoo, I'm good at computers:

```nix
{
#...
            hints.enabled = [{
              command = "true";
              regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\\\s{-}\\\\^⟨⟩`]+";
              mouse.enabled = false;
            }];
#...
}
```

or in lovely toml:

```toml

[[hints.enabled]]
command = "true"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^u0000-u001Fu007F-u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = false
```

good luck and god speed to anyone ever stumbling upon this.
