### ISSUE TITLE
Fonts are different compared to other terminals

### ISSUE THREAD

**Issue by rwxmad** [wez/wezterm#5331]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With this configuration, wezterm font is completely different compared to Alacritty, its similar to:
#3774, #689
```lua
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.automatically_reload_config = true

config.front_end = "WebGpu"

-- Window
config.window_decorations = "RESIZE"
config.window_background_opacity = 0.95
config.window_padding = {
  left = 2,
  right = 2,
  top = 2,
  bottom = 2,
}

config.hide_tab_bar_if_only_one_tab = true

-- Font
config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })
-- config.font_locator = "ConfigDirsOnly"
-- config.font_dirs = { os.getenv("HOME") .. "/dotfiles/fonts/BlexMono/ttf" }
-- config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })

config.font_size = 12.0

config.freetype_load_target = "HorizontalLcd"

-- Colorscheme
config.color_scheme_dirs = { os.getenv("HOME") .. "/.config/wezterm/colors" }
config.color_scheme = "Solarized"

config.bold_brightens_ansi_colors = true

return config
```

Alacritty:
![image](https://github.com/wez/wezterm/assets/30772868/42336650-57b1-413e-8fe5-bec554049ff1)
Wezterm:
![image](https://github.com/wez/wezterm/assets/30772868/6e77b0b1-f438-41bb-8faf-af5d625b77e4)

I try tune many options, but anyway don't have same result as in alacritty.
Like in #689, i try to specify font directory:
```lua
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.automatically_reload_config = true

config.front_end = "WebGpu"

-- Window
config.window_decorations = "RESIZE"
config.window_background_opacity = 0.95
config.window_padding = {
  left = 2,
  right = 2,
  top = 2,
  bottom = 2,
}

config.hide_tab_bar_if_only_one_tab = true

-- Font
-- config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })
config.font_locator = "ConfigDirsOnly"
config.font_dirs = { os.getenv("HOME") .. "/dotfiles/fonts/BlexMono/TTF" }
config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })

config.font_size = 12.0

config.freetype_load_target = "HorizontalLcd"

-- Colorscheme
config.color_scheme_dirs = { os.getenv("HOME") .. "/.config/wezterm/colors" }
config.color_scheme = "Solarized"

config.bold_brightens_ansi_colors = true

return config
```
But i get an error:
```
Unable to load a font specified by your font=wezterm.font('BlexMono Nerd
Font', {weight="Medium", stretch='Normal', style=Normal}) configuration.
Fallback(s) are being used instead, and the terminal may not render as
intended. An alternative variant of the font was requested; TrueType and
OpenType fonts don't have an automatic way to produce these font variants, so
a separate font file containing the bold or italic variant must be installed.
See https://wezfurlong.org/wezterm/config/fonts.html for more information

Unable to load a font specified by your font=wezterm.font('BlexMono Nerd
Font', {weight="Medium", stretch='Normal', style=Normal}) configuration.
Fallback(s) are being used instead, and the terminal may not render as
intended. An alternative variant of the font was requested; TrueType and
OpenType fonts don't have an automatic way to produce these font variants, so
a separate font file containing the bold or italic variant must be installed.
See https://wezfurlong.org/wezterm/config/fonts.html for more information
```
My Alacritty config:
```toml
live_config_reload = true

[env]
TERM = "alacritty"

[window]
opacity = 0.95
decorations = "None"
padding = { x = 2, y = 2 }

[scrolling]
history = 10000

[font]
size = 12.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x001217"
foreground = "0x708183"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"


[cursor]
vi_mode_style = {blinking = "Always"}

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]
```

### To Reproduce

Case with default font specified:
```lua
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.automatically_reload_config = true

config.front_end = "WebGpu"

-- Window
config.window_decorations = "RESIZE"
config.window_background_opacity = 0.95
config.window_padding = {
  left = 2,
  right = 2,
  top = 2,
  bottom = 2,
}

config.hide_tab_bar_if_only_one_tab = true

-- Font
config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })

config.font_size = 12.0

config.freetype_load_target = "HorizontalLcd"

-- Colorscheme
config.color_scheme_dirs = { os.getenv("HOME") .. "/.config/wezterm/colors" }
config.color_scheme = "Solarized"

config.bold_brightens_ansi_colors = true

return config
```
Case with custom font dir:
```lua
local wezterm = require("wezterm")

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.automatically_reload_config = true

config.front_end = "WebGpu"

-- Window
config.window_decorations = "RESIZE"
config.window_background_opacity = 0.95
config.window_padding = {
  left = 2,
  right = 2,
  top = 2,
  bottom = 2,
}

config.hide_tab_bar_if_only_one_tab = true

-- Font
config.font_locator = "ConfigDirsOnly"
config.font_dirs = { os.getenv("HOME") .. "/dotfiles/fonts/BlexMono/TTF" }
config.font = wezterm.font("BlexMono Nerd Font", { weight = "Medium" })

config.font_size = 12.0

config.freetype_load_target = "HorizontalLcd"

-- Colorscheme
config.color_scheme_dirs = { os.getenv("HOME") .. "/.config/wezterm/colors" }
config.color_scheme = "Solarized"

config.bold_brightens_ansi_colors = true

return config
```

### Configuration

like in reproduce section

### Expected Behavior

Font is displayed completely differently than in other terminals, in particular as in Alacritty with the same settings
