### ISSUE TITLE
dim effect from helix editor is showing bright in wezterm

### ISSUE THREAD

**Issue by masriomarm** [wez/wezterm#5570]
### What Operating System(s) are you seeing this problem on?

Windows, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

![Screenshot from 2024-06-16 14-54-57](https://github.com/wez/wezterm/assets/77388732/d68eba5d-7364-41a6-bb0f-11af82be3c2d)
I'm using [Helix editor](https://helix-editor.com/), when matching bracket pairs, matched pair is set to dim. as shown in the screen capture, you may notice the most right curly bracket just before end of line. main cursor is bright (but the out of focus causes it to be hollow)
This works normally on other terminals (Alacritty, windows-terminal) but not working on gnome-terminal.
I'm not sure what may cause the issue, or if there's a config to fix this.

### To Reproduce

1. launch `hx` 
2. configure your theme for dim matched pairs. save to  `~/.config/helix/themes/matchedpair.toml`, 
``` toml
inherits  = "tokyonight"

string = { fg= "light-green", modifiers = ["italic"] }

"ui.cursor" = { modifiers = ["dim", "reversed"] }
"ui.cursor.match" = { modifiers = ["dim", "reversed"] }
"ui.cursor.primary.normal" = { modifiers = ["reversed"] }
"ui.virtual.jump-label" = { modifiers = ["dim", "reversed"] }

# "ui.cursor" = { bg = "background_highlight" }
# "ui.cursor.match" = { bg = "background_highlight" }
# "ui.cursor.primary.normal" = { modifiers = ["reversed"] }

# "ui.statusline" = { fg = "foreground_highlight", bg = "background_highlight" }
# "ui.statusline.inactive" = { fg = "foreground", bg = "libadwaita_dark_alt" , modifiers = ["dim"] }

"ui.statusline.normal" = { fg = "dark_6", bg = "blue_3" }
"ui.statusline.insert" = { fg = "dark_6", bg = "green_3" }
"ui.statusline.select" = { fg = "dark_6", bg = "yellow_3" }

[palette]

libadwaita_dark_alt = "#303030" 
white = "#F6F5F4" # redifne clolor
# teal = "#93DDC2" # redifne clolor

blue_3 = "#3584E4"
green_3 = "#33D17A"
yellow_3 = "#F6D32D"
light_4 = "#DEDDDA"
dark_6 = "#000000"

```
3. in `hx` `:theme matchedpair.toml`

### Configuration

``` lua
config.color_scheme = 'tokyonight'
config.font = wezterm.font_with_fallback {
  'GoMono Nerd Font',
  'Fira Code',
}
```
Not sure if it's related to my configs, bu issue seems to persists across different color schemes.

### Expected Behavior

while in helix, matched pair should appear dim. Not bright.

### Anything else?

![Screenshot from 2024-06-16 14-54-57](https://github.com/wez/wezterm/assets/77388732/35d6fa00-7e27-44f1-bdb5-4c373227d51c)
ss shows wezterm on left, alacritty on right. you may notice difference in the most right curly bracket just before eol. alacritty shows a dim color while wezterm shows bright colors as primary cursor.
