### ISSUE TITLE
Font (Iosevka) looks kinda wide and low?

### ISSUE THREAD

**Issue by GoldsteinE** [wez/wezterm#689]
## Describe the bug

This is the same file, with same font (`ttf-iosevka` from AUR), opened in Wezterm nightly (left) and Alacritty (right).
![image](https://user-images.githubusercontent.com/12019211/114452720-7488c780-9be1-11eb-9cc4-72d6949a9c25.png)
Alacritty's rendering looks more slender and Iosevkaish, while Wezterm's is kinda wide and low. It's also observable from `tput cols`: it shows 86 for Alacritty and 79 for Wezterm when windows are the exact same size. `tput lines` is 36 for both Wezterm and Alacritty, but there's tab line in Wezterm, so it's actually 37.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210405-110924-a5bb5be8-85-gfcd7ceef
 - The active keyboard layout name: US English.

## To Reproduce

Dunno. I run fully-updated Arch Linux, with `wezterm-git` and `ttf-iosevka` from AUR, and `i3-gaps` as my WM. I'm not sure what exactly is causing this behaviour.

## Configuration

```lua
local w = require 'wezterm'

return {
    font = w.font('iosevka'),
    font_size = 16,
}
```

Also my Alacritty config in the case it helps:

```yaml
font:
  normal:
    family: Iosevka
  size: 11  # sic! I'm not sure why Wezterm requires 16 to get roughly same size
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false
```

## Expected behavior
Iosevka is rendered tall and slender, as it should be.
