### ISSUE TITLE
Some characters hugely oversized

### ISSUE THREAD

**Issue by pinpox** [wez/wezterm#699]
## Describe the bug
The following file:
```yaml




####OpenVPN####
container_template:
  name: "{{ item.name }}"
  network:
    - openvpn --ip "{{item.fixed_ip}}"
  state: present
```

Is rendered like this:
![image](https://user-images.githubusercontent.com/1719781/115009955-227bc680-9ead-11eb-8421-66e8afb73e2c.png)

Not sure why the `#` glyphs are so huge. 

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210405-110924-a5bb5be8-86-g776aedf9
 - colemak
 
## To Reproduce

Steps to reproduce the behavior.

Open the file pasted above in neovim+wezterm.

## Configuration

https://github.com/pinpox/nixos/blob/40cc6a6f991ea8def0ef999149d1838cf0012506/home-manager/modules/wezterm/wezterm.lua

## Expected behavior
![image](https://user-images.githubusercontent.com/1719781/115010224-71296080-9ead-11eb-86b7-e2d6410216fb.png)
